---
# tasks file for file_role
- name: print variable
  shell:
    cmd: |
      echo "Noms : {{ nom }}"
      echo "Prenoms: {{ prenoms}}"
  register: response

- name: display debug info
  debug:
    msg: "Response {{ response }}"

- name: manage files
  file:
    path: /home/alpha/Documents/ansible-alpha/file1
    state: touch
    owner: alpha
    group: alpha
    mode: 0777

- name: add line in file
  lineinfile:
    path: /home/alpha/Documents/ansible-alpha/file1
    regexp: "^Je"
    line: "Je m'appelle {{ nom }} {{ prenoms }} "
